apiVersion: v1
kind: Template
metadata:
  name: app-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: app-secrets
    labels:
      app: "${APP_NAME}"
  stringData:
    encryption-key: "${ENCRYPTION_KEY}"
parameters:
- name: APP_NAME
  value: manageiq
- name: ENCRYPTION_KEY
  from: "[a-zA-Z0-9]{43}"
  generate: expression
