apiVersion: v1
kind: Template
metadata:
  name: kafka-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: kafka-secrets
    labels:
      app: "${APP_NAME}"
  stringData:
    hostname: "${MESSAGING_HOSTNAME}"
    password: "${MESSAGING_PASSWORD}"
    username: "${MESSAGING_USERNAME}"
parameters:
- name: APP_NAME
  value: manageiq
- name: MESSAGING_HOSTNAME
  value: kafka
- name: MESSAGING_PASSWORD
  from: "[a-zA-Z0-9]{8}"
  generate: expression
- name: MESSAGING_USERNAME
  value: root
