apiVersion: v1
kind: Template
metadata:
  name: postgresql-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: postgresql-secrets
    labels:
      app: "${APP_NAME}"
  stringData:
    dbname: "${DATABASE_NAME}"
    hostname: "${DATABASE_HOSTNAME}"
    password: "${DATABASE_PASSWORD}"
    username: "${DATABASE_USER}"
    port: "${DATABASE_PORT}"
parameters:
- name: APP_NAME
  value: manageiq
- name: DATABASE_HOSTNAME
  value: postgresql
- name: DATABASE_NAME
  value: vmdb_production
- name: DATABASE_PASSWORD
  from: "[a-zA-Z0-9]{8}"
  generate: expression
- name: DATABASE_USER
  value: root
- name: DATABASE_PORT
  value: '5432'
