apiVersion: v1
kind: Template
metadata:
  name: rbac
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${APP_NAME}-orchestrator"
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${APP_NAME}-anyuid"
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${APP_NAME}-httpd"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: "${APP_NAME}-orchestrator"
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - pods/finalizers
    verbs:
    - "*"
  - apiGroups:
    - apps
    resources:
    - deployments
    - deployments/scale
    verbs:
    - "*"
  - apiGroups:
    - extensions
    resources:
    - deployments
    - deployments/scale
    verbs:
    - "*"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: "${APP_NAME}-orchestrator"
  roleRef:
    kind: Role
    name: "${APP_NAME}-orchestrator"
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: "${APP_NAME}-orchestrator"
parameters:
- name: APP_NAME
  value: manageiq
