apiVersion: v1
kind: Template
metadata:
  name: database-restore
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: database-restore-${ID}
  spec:
    template:
      metadata:
        name: database-restore-${ID}
      spec:
        containers:
        - name: postgresql
          image: docker.io/manageiq/postgresql:10
          command:
          - "/opt/manageiq/container-scripts/restore_db"
          env:
          - name: BACKUP_VERSION
            value: "${DATABASE_BACKUP_VERSION}"
          - name: DATABASE_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: hostname
          - name: DATABASE_PORT
            value: "${DATABASE_PORT}"
          volumeMounts:
          - name: backup
            mountPath: "/backups"
          - name: production
            mountPath: "/restore"
        volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: postgresql-backup
        - name: production
          persistentVolumeClaim:
            claimName: postgresql
        restartPolicy: Never
parameters:
- name: DATABASE_BACKUP_VERSION
  value: latest
- name: DATABASE_PORT
  value: '5432'
- name: ID
  from: "[a-z0-9]{8}"
  generate: expression
