apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv02
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /exports/miq-pv02
    server: <your-nfs-host-here>
  persistentVolumeReclaimPolicy: Recycle
