# permissions for end users to view manageiqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manageiq-viewer-role
rules:
- apiGroups:
  - manageiq.org
  resources:
  - manageiqs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manageiq.org
  resources:
  - manageiqs/status
  verbs:
  - get
