apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manageiq-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manageiq-operator
subjects:
- kind: ServiceAccount
  name: manageiq-operator
