apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageiq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manageiq-operator
  template:
    metadata:
      labels:
        name: manageiq-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      serviceAccountName: manageiq-operator
      containers:
        - name: manageiq-operator
          image: docker.io/manageiq/manageiq-operator:latest-quinteros
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: 60Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 100m
