#!/bin/bash

[[ -s ${APP_ROOT}/container_env ]] && source ${APP_ROOT}/container_env

echo "== Writing encryption key =="
cat > /var/www/miq/vmdb/certs/v2_key << KEY
---
:algorithm: aes-256-cbc
:key: ${ENCRYPTION_KEY}
KEY

echo "${GUID}" > ${APP_ROOT}/GUID

[[ -n $EMS_IDS ]] && WORKER_OPTIONS="--ems-id=${EMS_IDS} "

exec ruby ${APP_ROOT}/lib/workers/bin/run_single_worker.rb --heartbeat ${WORKER_OPTIONS}${WORKER_CLASS_NAME}
