ARG FROM_REPO=docker.io/manageiq
ARG FROM_TAG=latest-spassky

FROM ${FROM_REPO}/manageiq-webserver-worker:${FROM_TAG}

LABEL name="manageiq-ui-worker" \
      summary="ManageIQ user interface worker image"
