// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManageIQ) DeepCopyInto(out *ManageIQ) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManageIQ.
func (in *ManageIQ) DeepCopy() *ManageIQ {
	if in == nil {
		return nil
	}
	out := new(ManageIQ)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManageIQ) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManageIQList) DeepCopyInto(out *ManageIQList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManageIQ, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManageIQList.
func (in *ManageIQList) DeepCopy() *ManageIQList {
	if in == nil {
		return nil
	}
	out := new(ManageIQList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManageIQList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManageIQSpec) DeepCopyInto(out *ManageIQSpec) {
	*out = *in
	if in.EnforceWorkerResourceConstraints != nil {
		in, out := &in.EnforceWorkerResourceConstraints, &out.EnforceWorkerResourceConstraints
		*out = new(bool)
		**out = **in
	}
	if in.EnableSSO != nil {
		in, out := &in.EnableSSO, &out.EnableSSO
		*out = new(bool)
		**out = **in
	}
	if in.EnableApplicationLocalLogin != nil {
		in, out := &in.EnableApplicationLocalLogin, &out.EnableApplicationLocalLogin
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManageIQSpec.
func (in *ManageIQSpec) DeepCopy() *ManageIQSpec {
	if in == nil {
		return nil
	}
	out := new(ManageIQSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManageIQStatus) DeepCopyInto(out *ManageIQStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManageIQStatus.
func (in *ManageIQStatus) DeepCopy() *ManageIQStatus {
	if in == nil {
		return nil
	}
	out := new(ManageIQStatus)
	in.DeepCopyInto(out)
	return out
}
