apiVersion: manageiq.org/v1alpha1
kind: Manageiq
metadata:
  name: miq
spec:
  # Add fields here
  appName: # e.g. "manageiq"
  applicationAdminPassword: # e.g. "smartvm"
  applicationDomain: # e.g. "miqproject.example.com"

  databaseSecret: postgresql-secrets
  databaseRegion: # e.g. "0"
  databaseVolumeCapacity: # e.g. 15Gi

  httpdCpuRequest: # e.g. 100m
  httpdImageName: # e.g. manageiq/httpd
  httpdImageTag: # e.g. latest
  httpdMemoryLimit: # e.g. 200Mi
  httpdMemoryRequest: # e.g. 100Mi

  memcachedCpuRequest: # e.g. 200m
  memcachedImageName: # e.g. manageiq/memcached
  memcachedImageTag: # e.g. latest 

  memcachedMaxConnection: # e.g. "1024"
  memcachedMaxMemory: # e.g. "64"
  memcachedMemoryLimit: # e.g. 256Mi
  memcachedMemoryRequest: # e.g. 64Mi
  memcachedSlabPageSize: # e.g. 1m

  orchestratorCpuRequest: # e.g. 100m
  orchestratorImageName: # e.g. manageiq-orchestrator
  orchestratorImageNamespace: # e.g. manageiq
  orchestratorImageTag: # e.g. latest
  orchestratorMemoryLimit: # e.g. 16Gi
  orchestratorMemoryRequest: # e.g. 150Mi

  postgresqlCpuRequest: # e.g. 100m
  postgresqlImageName: # e.g. docker.io/manageiq/postgresql
  postgresqlImageTag: # e.g. latest
  postgresqlMaxConnections: # e.g. "1000" 
  postgresqlMemoryLimit: # e.g. 8Gi
  postgresqlMemoryRequest: # e.g. 200Mi
  postgresqlSharedBuffers: # e.g. 1GB

  kafkaSecret: kafka-secrets
  kafkaVolumeCapacity: 1Gi
  zookeeperVolumeCapacity: 1Gi
