apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv04
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /exports/miq-pv04
    server: <your-nfs-host-here>
  persistentVolumeReclaimPolicy: Retain
