ARG FROM_REPO=manageiq
ARG FROM_TAG=latest

FROM ${FROM_REPO}/manageiq-base-worker:${FROM_TAG}
MAINTAINER ManageIQ https://manageiq.org

LABEL name="manageiq-webserver-worker" \
      summary="ManageIQ web server worker image"

EXPOSE 3000
