#!/bin/bash

# Cleanup dnf
dnf clean all
rm -rf /var/cache/dnf
# Intentionally keeping the sqlite database to preserve metadata about where packages were sourced from.
rm -rf /var/lib/dnf/history.sqlite-*
rm -rf /var/log/dnf*.log
rm -rf /var/log/hawkey.log

# Cleanup rpm
rm -rf /var/lib/rpm/__db.*
