#!/bin/bash

OPTIONS="$MEMCACHED_EXTRA_PARAMETERS"

if [ -n "${MEMCACHED_MAX_MEMORY}" ]; then
  OPTIONS+=" -m $MEMCACHED_MAX_MEMORY"
fi

if [ -n "${MEMCACHED_MAX_CONNECTIONS}" ]; then
  OPTIONS+=" -c $MEMCACHED_MAX_CONNECTIONS"
fi

if [ -n "${MEMCACHED_SLAB_PAGE_SIZE}" ]; then
  OPTIONS+=" -I $MEMCACHED_SLAB_PAGE_SIZE"
fi

set -eu
echo "Starting memcached with : $@ ${OPTIONS}"
exec "$@" ${OPTIONS}
