name: Build Pods
on:
  repository_dispatch:
    types:
    - build
  workflow_dispatch:
jobs:
  build_pods:
    if: github.repository_owner == 'ManageIQ'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'manageiq-operator/go.mod'
    - name: Docker login
      run: echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login docker.io --password-stdin --username ${{ secrets.DOCKER_REGISTRY_USERNAME }}
    - name: Build pods containers
      run: bin/build -t latest -n -p
  notify_builders:
    needs: build_pods
    if: github.repository_owner == 'ManageIQ'
    runs-on: ubuntu-latest
    steps:
    - name: Notify manageiq on pods build
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.BUILD_TOKEN }}
        repository: ManageIQ/manageiq
        event-type: build
        client-payload: |
          { "repository": "${{ github.repository }}",
            "ref_name": "${{ github.ref_name }}",
            "sha": "${{ github.sha }}" }
