name: Build Pods
on:
  repository_dispatch:
    types:
    - build
jobs:
  build_pods:
    if: github.repository_owner == 'ManageIQ'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'manageiq-operator/go.mod'
    - name: Docker login
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login docker.io --password-stdin --username ${{ secrets.REGISTRY_USERNAME }}
    - name: Build pods containers
      run: bin/build -t latest -n -p
